-- SQLITE IMPORT SCRIPT for Entertainment Tadka Bot
-- Run this in SQLite console to sync all movies to analytics

-- First, clear old analytics (if needed)
DELETE FROM uploads;

-- Now insert all movies from your CSV (177 movies)
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Mandala Murders', 6, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-23');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Mandala Murders', 7, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-23');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Mandala Murders', 8, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-23');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 9, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 10, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 11, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 12, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 13, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Zebra 2024', 14, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-29');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 15, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 16, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 17, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 18, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 19, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 20, '720p', '1.5GB', 'Hindi', 'Movie', '2025-10-30');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 21, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Show Time 2025', 22, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 23, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 24, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 25, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 26, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 27, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 28, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Andhadhun 2018', 29, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Lokah Chapter 1 Chandra 2025', 30, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Lokah Chapter 1 Chandra 2025', 31, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Lokah Chapter 1 Chandra 2025', 32, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Lokah Chapter 1 Chandra 2025', 33, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Lokah Chapter 1 Chandra 2025', 34, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 35, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 36, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 37, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 38, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 39, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Idli Kadai (2025)', 40, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-01');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 41, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 42, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 43, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 44, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 45, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 46, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 47, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 48, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 49, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Bachhala Malli', 50, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Rangeen', 51, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Rangeen', 52, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Rangeen', 53, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 54, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 55, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 56, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 57, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 58, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 59, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 60, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Seesaw', 61, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Joker 2012', 62, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-19');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Joker 2012', 65, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Joker 2012', 66, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Joker 2012', 63, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-19');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Joker 2012', 64, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-19');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S01 2019', 69, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S01 2019', 70, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S01 2019', 71, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S01 2019', 72, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S02 2022', 67, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S02 2022', 68, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-20');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S03 2025', 73, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-21');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S03 2025', 74, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-21');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('The Family Man S03 2025', 75, '720p', '1.5GB', 'Hindi', 'Series', '2025-11-21');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 76, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 77, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 78, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 79, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 80, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Narivetta (2025)', 81, '720p', '1.5GB', 'Hindi', 'Movie', '2025-11-22');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 82, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 83, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 84, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 85, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 86, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 87, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 88, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 89, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Pechi', 90, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-02');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 91, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 92, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 93, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 94, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 95, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Gurthunda Seethakalam', 96, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-03');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 97, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 98, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 99, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 100, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 101, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 102, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 103, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 104, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 105, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Fear', 106, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-04');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 107, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 108, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 109, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 110, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 111, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 112, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Revenge', 113, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-05');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 114, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 115, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 116, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 117, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 118, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 119, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Kuladalli Keelyavudo', 120, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-06');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 121, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 122, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 123, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 124, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 125, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 126, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 127, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 128, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('DNA', 129, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-07');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 130, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 131, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 132, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 133, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 134, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 135, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 136, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 137, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 138, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 139, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 140, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 141, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Moonwalk', 142, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 143, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 144, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 145, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 146, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 147, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 148, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 149, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Robinhood', 150, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-10');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 151, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 152, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 153, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 154, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 155, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 156, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 157, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 158, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 159, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 160, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Thug Life', 161, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-11');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 162, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 163, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 164, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 165, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 166, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 167, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ek Chatur Naar Chathuram', 168, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-12');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 169, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 170, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 171, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 172, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 173, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 174, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 175, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 176, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');
INSERT INTO uploads (file_name, message_id, quality, file_size, language, category, upload_date) VALUES ('Ace', 177, '720p', '1.5GB', 'Hindi', 'Movie', '2025-12-14');

-- Verify the import
SELECT '✅ Import Complete!' as Status;
SELECT COUNT(*) as 'Total Movies Imported' FROM uploads;
